name: Build Workflow
on: [ push, pull_request ]

jobs:
  build:
    name: Build (C++${{ matrix.cpp_standard }}, Header Only ${{ matrix.use_header_only }}, ${{ matrix.config }})
    runs-on: windows-latest

    strategy:
      matrix:
        cpp_standard: [ 20, 23 ]
        use_header_only: [ NO, YES ]
        config: [ Debug, Release, MinSizeRel, RelWithDebInfo ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create build directory
        run: mkdir build

      - name: Configure
        working-directory: build
        run: |
          cmake `
            -DCMAKE_CXX_STANDARD=${{ matrix.cpp_standard }} `
            -DRED4EXT_HEADER_ONLY=${{ matrix.use_header_only }} `
            -DRED4EXT_BUILD_EXAMPLES=ON `
            ${{ github.workspace }}

      - name: Build
        working-directory: build
        run: |
          cmake `
            --build . `
            --config ${{ matrix.config }}
