name: Build Workflow
on: [ push, pull_request ]

jobs:
  build:
    name: Build (${{ matrix.config }})
    runs-on: windows-latest

    strategy:
      matrix:
        config: [ Debug, Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Generate project
        run: |
          cd premake
          ./generate_project.bat

      - name: Build
        run: |
          cd premake/project
          MSBuild.exe RED4ext.SDK.sln -v:minimal -m -property:Configuration=${{ matrix.config }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RED4ext-${{ matrix.config }}
          path: build/${{ matrix.config }}/
